server:
  port: 8527

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    password:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/what_to_eat?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 962464
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters
      filters: stat

# swagger
swagger:
  host: 127.0.0.1
  basic:
    enable: true
    username: whattoeat
    password: whattoeat


#jsontoken
jwt:
  subject: com.what.to.eat
  # 48小时 8 * 3600 * 1000
  life: 172800000
  secret: 674df897d4f59f93e2815e04cf2185af36213476a5bdc14c6e1f5a5b9c34b48d4def4ff25fdcefdab150cdc8508a803bcede4f1651c966f37289c3efb437e8bb

